// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Models;

namespace WebApi.Migrations
{
    [DbContext(typeof(DelegiranjeContext))]
    [Migration("20220314161130_v4")]
    partial class v4
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.12")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MecSudija", b =>
                {
                    b.Property<int>("SpojMecMecID")
                        .HasColumnType("int");

                    b.Property<int>("SpojSudijaID")
                        .HasColumnType("int");

                    b.HasKey("SpojMecMecID", "SpojSudijaID");

                    b.HasIndex("SpojSudijaID");

                    b.ToTable("MecSudija");
                });

            modelBuilder.Entity("MecTim", b =>
                {
                    b.Property<int>("SpojMeceviMecID")
                        .HasColumnType("int");

                    b.Property<int>("SpojTimID")
                        .HasColumnType("int");

                    b.HasKey("SpojMeceviMecID", "SpojTimID");

                    b.HasIndex("SpojTimID");

                    b.ToTable("MecTim");
                });

            modelBuilder.Entity("Models.Delegat", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BrLicence")
                        .HasColumnType("int");

                    b.Property<string>("Ime")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("Liga")
                        .HasColumnType("int");

                    b.Property<string>("Prezime")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ID");

                    b.ToTable("Delegati");
                });

            modelBuilder.Entity("Models.Mec", b =>
                {
                    b.Property<int>("MecID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Datum")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DelegatID")
                        .HasColumnType("int");

                    b.Property<int>("Kolo")
                        .HasColumnType("int");

                    b.HasKey("MecID");

                    b.HasIndex("DelegatID");

                    b.ToTable("Mecevi");
                });

            modelBuilder.Entity("Models.Sudija", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BrLicence")
                        .HasColumnType("int");

                    b.Property<string>("Ime")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("PolozajSudije")
                        .HasColumnType("int");

                    b.Property<string>("Prezime")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("RdBrLige")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("Sudija");
                });

            modelBuilder.Entity("Models.Tim", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Ime")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ImeKapitena")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Mesto")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("RangLige")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("Timovi");
                });

            modelBuilder.Entity("MecSudija", b =>
                {
                    b.HasOne("Models.Mec", null)
                        .WithMany()
                        .HasForeignKey("SpojMecMecID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Models.Sudija", null)
                        .WithMany()
                        .HasForeignKey("SpojSudijaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MecTim", b =>
                {
                    b.HasOne("Models.Mec", null)
                        .WithMany()
                        .HasForeignKey("SpojMeceviMecID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Models.Tim", null)
                        .WithMany()
                        .HasForeignKey("SpojTimID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Models.Mec", b =>
                {
                    b.HasOne("Models.Delegat", "Delegat")
                        .WithMany("Mec")
                        .HasForeignKey("DelegatID");

                    b.Navigation("Delegat");
                });

            modelBuilder.Entity("Models.Delegat", b =>
                {
                    b.Navigation("Mec");
                });
#pragma warning restore 612, 618
        }
    }
}
