// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Models;

namespace WebApi.Migrations
{
    [DbContext(typeof(DelegiranjeContext))]
    [Migration("20220312183341_V1")]
    partial class V1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.12")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Models.Delegat", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Ime")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("Liga")
                        .HasColumnType("int");

                    b.Property<string>("Prezime")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ID");

                    b.ToTable("Delegati");
                });

            modelBuilder.Entity("Models.Mec", b =>
                {
                    b.Property<int>("MecID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Datum")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DelegatID")
                        .HasColumnType("int");

                    b.Property<int>("Kolo")
                        .HasColumnType("int");

                    b.HasKey("MecID");

                    b.HasIndex("DelegatID");

                    b.ToTable("Mecevi");
                });

            modelBuilder.Entity("Models.SpojSM", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("MecID")
                        .HasColumnType("int");

                    b.Property<int?>("SudijaID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("MecID");

                    b.HasIndex("SudijaID");

                    b.ToTable("SpojeviSM");
                });

            modelBuilder.Entity("Models.SpojTM", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("MecID")
                        .HasColumnType("int");

                    b.Property<int?>("TimID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("MecID");

                    b.HasIndex("TimID");

                    b.ToTable("SpojeviTM");
                });

            modelBuilder.Entity("Models.Sudija", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Ime")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("PolozajSudije")
                        .HasColumnType("int");

                    b.Property<string>("Prezime")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("RdBrLige")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("Sudija");
                });

            modelBuilder.Entity("Models.Tim", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Ime")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ImeKapitena")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Mesto")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ID");

                    b.ToTable("Timovi");
                });

            modelBuilder.Entity("Models.Mec", b =>
                {
                    b.HasOne("Models.Delegat", "Delegat")
                        .WithMany("Mec")
                        .HasForeignKey("DelegatID");

                    b.Navigation("Delegat");
                });

            modelBuilder.Entity("Models.SpojSM", b =>
                {
                    b.HasOne("Models.Mec", "Mec")
                        .WithMany("SpojSudija")
                        .HasForeignKey("MecID");

                    b.HasOne("Models.Sudija", "Sudija")
                        .WithMany("SpojMec")
                        .HasForeignKey("SudijaID");

                    b.Navigation("Mec");

                    b.Navigation("Sudija");
                });

            modelBuilder.Entity("Models.SpojTM", b =>
                {
                    b.HasOne("Models.Mec", "Mec")
                        .WithMany("SpojTim")
                        .HasForeignKey("MecID");

                    b.HasOne("Models.Tim", "Tim")
                        .WithMany("SpojMecevi")
                        .HasForeignKey("TimID");

                    b.Navigation("Mec");

                    b.Navigation("Tim");
                });

            modelBuilder.Entity("Models.Delegat", b =>
                {
                    b.Navigation("Mec");
                });

            modelBuilder.Entity("Models.Mec", b =>
                {
                    b.Navigation("SpojSudija");

                    b.Navigation("SpojTim");
                });

            modelBuilder.Entity("Models.Sudija", b =>
                {
                    b.Navigation("SpojMec");
                });

            modelBuilder.Entity("Models.Tim", b =>
                {
                    b.Navigation("SpojMecevi");
                });
#pragma warning restore 612, 618
        }
    }
}
